name: Algorithms Build and Deploy

on:
  push:
    branches: 
      - main
    paths:
      - 'DataStructuresAndAlgorithms/Algorithms/**'
  pull_request:
    branches:
      - main
    paths:
      - 'DataStructuresAndAlgoriths/Algoriths/**'
      
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]

    env:
      solution: './DataStructuresAndAlgorithms/Algorithms/Algorithms.sln'
      package: './DataStructuresAndAlgorithms/Algorithms/Algorithms/Algorithms.csproj'
      output: 'Packages/Staging/DataStructuresAndAlgorithms/Algorithms'

    steps:
    - name: Checkout
      uses: actions/checkout@v2      

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies      
      run: dotnet restore ${{ env.solution }}

    - name: Build project 
      run: dotnet build ${{ env.solution }} --no-restore --configuration Release

    - name: Run Unit Tests
      run: dotnet test ${{ env.solution }}

    - name: Deploy to staging
      run: dotnet publish ${{ env.package }} -c Release
