name: Algorithms Build and Deploy

on:
  push:
    branches: 
      - main
    paths:
      - 'DataStructuresAndAlgorithms/**'
  pull_request:
    branches:
      - main
    paths:
      - 'DataStructuresAndAlgoriths/**'
      
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    env:
      solution: './DataStructuresAndAlgorithms/Algorithms/Algorithms.sln'
      package: './DataStructuresAndAlgorithms/Algorithms/Algorithms/Algorithms.csproj'
      output: './Packages/Staging/DataStructuresAndAlgorithms'

    steps:
    - name: Checkout
      uses: actions/checkout@v2      

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies      
      run: dotnet restore ${{ env.solution }}

    - name: Build project 
      run: dotnet build ${{ env.solution }} --no-restore --configuration Release

    - name: Run Unit Tests
      run: dotnet test ${{ env.solution }}

    - name: Deploy to staging
      run: |
        dotnet publish ${{ env.package }} -c Release -o ${{ env.output }} |
        mkdir Publish
    
    - name: Create artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.output }}
        name: published-package
