name: Data Structures and Algorigthms Build

on:
  pull_request:
    paths:
      - '/Data%20Structures%20and%20Algorithms/Algorithms/**'
  workflow_dispatch:
  
  

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: .\Data%20Structures%20and%20Algorithms\Algorithms\Algorithms.sln
      Test_Project_Path: .\Data%20Structures%20and%20Algorithms\Algorithms\Algorithms.Tests\Algorithms.Tests.csproj      

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build project 
      run: dotnet build {{ env.Solution_Name }}
